In [5]:
import numpy as np

In [6]:
arr1= np.array([3,4,6,7,0]) # n dimenssion array
print(type(arr1)) #getting the type of array
print(arr1)

print('\n')
arr2 = np.array([[1,2,3,4],[2,4,6,8,]])
print(type(arr2)) #if float then print 0 because datatype is 'int32'
print(arr2)


<class 'numpy.ndarray'>
[3 4 6 7 0]


<class 'numpy.ndarray'>
[[1 2 3 4]
 [2 4 6 8]]


In [15]:
#array multiplicaton 
mul=arr2*arr2   #Mulpication is done by element wise not by matrics
print(mul)

print("\n")
#addition of arrays
add=arr2+arr2   #Mulpication is done by element wise not by matrics
print(add)

[[ 1  4  9 16]
 [ 4 16 36 64]]


[[ 2  4  6  8]
 [ 4  8 12 16]]


In [23]:
#making new array 
a=np.array([12**12])
print(a)

#changing the datatype
a=np.array([12**12], dtype='int32')
print(a) #gives error beacuase datatype is not the type of 

[8916100448256]


OverflowError: Python int too large to convert to C long

In [7]:
a1=arr2.shape # gives in the form of [rows,column]
print(a1)
print('\n')
a2=arr2.dtype #gives data type
print(a2)

(2, 4)


int32


In [10]:
#arrray creating functions
a4=np.zeros((4,7)) #this acpt arguments in the form of tupple. used for making arrays
print(a4)

print("\n")
a5=np.empty((4,6))
print(a5)

# difference beween the function np.zeros and np.empty
# np.zeros -> Always contains zeros '0'
# np.empty -> They can contain zero or garbage value. But most of the time they are zeros. And directly allocates the memory to the array



[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


[[4.67296746e-307 1.69121096e-306 1.29060871e-306 4.45061456e-308
  1.95822253e-306 7.56597770e-307]
 [9.34577196e-307 1.37962456e-306 1.60216183e-306 7.56602523e-307
  1.33511562e-306 1.37959129e-306]
 [9.34609111e-307 4.22793232e-307 4.45052544e-308 2.22522597e-306
  6.23059386e-307 2.22522597e-306]
 [1.33511969e-306 1.42419666e-306 1.39070936e-307 1.39075434e-307
  8.90068250e-307 1.16820452e-307]]


In [34]:
t1=np.zeros(4).dtype #type
print(t1) # type of upper line
print('\n')
t2 = np.ones(6).dtype
print(t2)

float64


float64


##Slicing

In [75]:
arr=np.array([1,2,3,4,5,6])
print(f"Real Array is {arr}")

print('\nSlicing function 1...')
#Slicing function 1 this will give the elements from index 2 to 5
b=arr[2:5] #this will give the elements from index 2 to 5
print(f"Elements of array got between index 0 to 5 (After Slicing): {b}")

print("\nChanging the values")
#changing the value at
b[0]=11
print(f"Values got change in Sliced Array at index 0(which get reflected in Real Array) {b}") #this get change but also get change
print(f"Values got change in real Array at index 2: {arr}")

Real Array is [1 2 3 4 5 6]

Slicing function 1...
Elements of array got between index 0 to 5 (After Slicing): [3 4 5]

Changing the values
Values got change in Sliced Array at index 0(which get reflected in Real Array) [11  4  5]
Values got change in real Array at index 2: [ 1  2 11  4  5  6]
