In [9]:
import numpy as np

In [10]:
arr1 = np.array([[1,2,4],
                 [2,4,6]])
print(f"Real Array is \n{arr1}")

#adding operation using axis function
print("\nUsing the axis function...")
add_colm=arr1.sum(axis=0) #Add column wise
print(f"Adding Column Wise: {add_colm}")
add_row=arr1.sum(axis=1) #Add Row wise
print(f"Adding Row Wise: {add_row}")


Real Array is 
[[1 2 4]
 [2 4 6]]

Using the axis function...
Adding Column Wise: [ 3  6 10]
Adding Row Wise: [ 7 12]


In [16]:
# Dot and Cross Product.
arr2 = np.array([[1,2,4],
                 [7,2,1]])
#dir(np)            for getting the function  of numpy

print("Dot Product of arr1 and arr2 is \n",np.dot(arr1,arr2.transpose())) #funtion for getting the dot product

print("\nAnd Cross Product is \n",np.cross(arr1,arr2))    #Function for cross product


Dot Product of arr1 and arr2 is 
 [[21 15]
 [34 28]]

And Cross Product is 
 [[  0   0   0]
 [ -8  40 -24]]


In [29]:
#Sorting Function
print(f"Real array\n{arr2}")

a=np.sort(arr2) #this will sort in row-row 
# np.sort(arr2, axis=1) this is aliter of upper line
print("\n",a)

b=np.sort(arr2,axis =0, kind="mergsort") # this will sort column-column, Kind wil reduce time
print("\n",b)

Real array
[[1 2 4]
 [7 2 1]]

 [[1 2 4]
 [1 2 7]]

 [[1 2 1]
 [7 2 4]]
