In [9]:
#Numpy argsort, argmin, Argmax and other tips
import numpy as np



In [58]:
arr1=np.arange(8) 
print("This is a Array1(Numpy arange func): ",a)

b=np.array([1,23,45,6,8,45,3,4,3,2,1,4,2,3,6,4,2,11])
print("\nThis is Array2(Numpy array Func): \n",b)

b0=np.shape(b) #This will give the size of array

print(f"Size of Array2: f{b0}")

b1=b.reshape(2,9) #Here the number of elemets are 18, calculation is done like m*n= 2*9
print(f"After reshapig the Array2 in the form 2*9(m*n):\n {b1}")

sort = np.argsort(b) #This will sort in ascending order but gives the index
print("Sorting acc to INDEX: ",sort)

a1=np.argmin(b) #gives index of minimum number
print(f"\nThe index of minimun number of Array2: {a1}")
a1=np.argmax(b)     #gives index of maximum number
print("The index of Maximmum number: ",a1)





This is a Array1(Numpy arange func):  [0 1 2 3 4 5 6 7 8]

This is Array2(Numpy array Func): 
 [ 1 23 45  6  8 45  3  4  3  2  1  4  2  3  6  4  2 11]
Size of Array2: f(18,)
After reshapig the Array2 in the form 2*9(m*n):
 [[ 1 23 45  6  8 45  3  4  3]
 [ 2  1  4  2  3  6  4  2 11]]
Sorting acc to INDEX:  [ 0 10 12  9 16 13  8  6  7 11 15  3 14  4 17  1  5  2]

The index of minimun number of Array2: 0
The index of Maximmum number:  2
